---
title: "História do Seguro"
---

```{r setup, include=FALSE}
source("setup_knitr.R")
```

<br>

# As origens do seguro

\ \ \ \ \ \ As origens do seguro e a busca pela preservação da própria vida contra riscos iminentes podem se confundir ao longo dos séculos. É comum encontrarmos relatos acerca de relações de mutualismo entre comerciantes cameleiros na Babilônia, cerca de 25 séculos antes de Cristo, como as primeiras relações que poderiam caracterizar um acordo de seguro, por meio da assistência mutualística<sup>1</sup>. Um grupo de cameleiros, que cruzava o deserto, contabilizava quantos camelos haviam partido com a expedição e quantos chegaram vivos. Então, os integrantes do grupo dividiam, entre si, as perdas sofridas, comprando novos camelos para aqueles que haviam perdido o seu durante a viagem.  

\ \ \ \ \ \ Outros relatos recorrentes quanto à história do seguro no mundo, são as referências ao Código de Hamurábi<sup>2</sup>  e as Leis de Rodes<sup>3</sup> , documentos importantes na história da humanidade que demonstram que a história do seguro vem acompanhando o desenvolvimento do convívio social humano desde de tempos remotos. O Código de Hamurábi, baseado na antiga Lei de Talião, “olho por olho e dente por dente”, prevendo uma punição considerada proporcional a cada ato criminoso, contemplava leis civis militares, políticas e comerciais, promovendo a fundação de uma associação que ficaria encarregada de adquirir novos barcos ou burros aos comerciantes que perdessem os seus em decorrência de tempestades, protegendo, assim, tanto os comerciantes navegantes, quanto aos membros de caravanas que cruzavam os desertos da região. Também as Leis de Rodes, editadas 200 anos antes da fundação de Roma no século VII A.C., também regula o mutualismo em transportes marítimos, repartindo prejuízos entre os donos da embarcação e os donos da carga, sendo possível observar nelas, princípios que regem a atual Avaria Grossa<sup>4</sup>.   

\ \ \ \ \ \ O instinto natural de sobrevivência, porém, é muito mais antigo que qualquer relato ou registro histórico. Sinais da preocupação do homem em se resguardar são encontrados desde a Pré-história, como os primeiros hominídeos eram nômades, os perigos eram constantes. Assim, o perigo, a insegurança, a incerteza e o medo já se faziam presentes na vida do homem. O homem primitivo tinha de se proteger não só de predadores e pragas, mas também de terremotos, incêndios, raios e chuvas, o que pode ser considera uma forma ancestral do autosseguro. A evolução natural foi a busca pelo convívio em grupo e com morada fixa, o que oportunizou, não só a divisão de tarefas, mas também o mutualismo, que, de certa forma, é capaz de substituir o autosseguro, pois as perdas, neste contexto, não são mais individuais, mas de todo o grupo.   

\ \ \ \ \ \ O mutualismo foi a base para as regras de divisão de perdas previstas no Código de Hamurábi e nas Leis de Rodes e também nas collegia tenuiorum (sociedades funerárias) fundadas durante o Império Romano. Os romanos organizaram serviços funerários e de beneficência, assemelhados, atualmente, aos montepios. Os membros dessa collegia contribuíam, antecipadamente, para a criação de um fundo que cobria as despesas do enterro (AZEVEDO, G. H. W., 2008). Criaram também, a collegia militum, destinada a “conceder pensões aos membros que se encontrassem em situações de incapacidade provocada por feridas sofridas em combate, ou outorgava pensões de reforma a quem atingisse o limite de sua idade militar” (LARRAMENDI et al., 1991, In: AZEVEDO, G. H. W., 2008).   

\ \ \ \ \ \ Desde então, diversas sociedades de caráter assitencial, mais tardes transformadas em associações de seguros mútuos, foram fundadas, principalmente nos séculos X e XI, particularmente para reparar desequilíbrios financeiros ocasionados por desaparecimentos de bens móveis, escravos ou gados, incêndios e especialmente perdas nos transportes marítimos. Era comum que um navegador pegasse de empréstimo certa quantia em dinheiro para financiar sua viagem, dando em garantia seu navio, caso, ao fim da viagem, a carga chegasse ao porto, o empréstimo era pago acrescido de “juros náuticos”; caso contrário, a obrigação do pagamento cessava. Prática que foi proibida pelo papa Gregório IX em 1234, que por meio do Direito Canônico, determinou que tal prática era usura, ou sacrilégio, pois segundo o clero, apenas a vontade divina seria capaz de minimizas as desgraças e infortúnios do homem.  

\ \ \ \ \ \ Com a proibição do seguro marítimo, os banqueiros da época criaram um mecanismo criativo para continuar a realizar o mutualismo. Eles passaram a “comprar” navio e carga. Caso nada acontecesse nem com a carga, nem com o navio, o contrato era quebrado, obrigando o navegador a repor o valor do contrato acrescido de uma multa contratual equivalente aos juros sobre o capital. Em caso de sinistro<sup>5</sup> , os navegantes ficavam com o dinheiro e o banqueiro com o prejuízo.   
 
\ \ \ \ \ \ Deste contrato de compra originaram-se as atuais apólices de seguro, sendo a primeira emitida no ano de 1347 na cidade italiana de Gênova, uma apólice de seguro marítimo, um dos mais antigos e que serviu de base para o desenvolvimento de vários outros.   
 
<br>

# Seguro no Brasil

 
\ \ \ \ \ \ Em 1810, Visconde Cairu<sup>6</sup> já dizia que o comércio de seguros é um dos mais beneméritos da humanidade, especialmente quando seu objetivo é o amparo à viúva, do órfão, do velho e do jornaleiro, pobre ou debilitado pelo trabalho.   
 
\ \ \ \ \ \ Apenas 2 anos antes da fala de Cairu, o Brasil começaria a ser levado a sério com a vinda da Corte portuguesa, elevando a então colônia a condição de Reino Unido de Portugal e Algarves. Época que marca o início do desenvolvimento brasileiro, pois até então não se podiam instalar indústrias nas terras coloniais, todos os produtos manufaturados eram importados da Metrópole.  
 
\ \ \ \ \ \ A chegada da Família Real no Brasil em 1808, e a consequente abertura econômica que isso provocou, com a liberação dos portos às nações amigas e as relações internacionais que foram estabelecidas, fez com que os seguros surgissem no país. Nesse ano foi criada na Bahia a primeira seguradora brasileira, a Companhia de Seguros Boa-Fé, regulada e dirigida pela Casa de Seguros de Lisboa. Na sequência, também em território baiano, a Companhia de Seguros Conceito Público e, já em território fluminense, no ano de 1810, a seguradora Identidade, tiveram seu funcionamento autorizado. Todas estas restritas ao seguro para comércio marítimo.  
 
\ \ \ \ \ \ Até a Independência do Brasil, em 1822, todas as companhias seguradoras fundadas eram subordinadas às normas da Casa de Seguros de Lisboa. Porém, mesmo com a independência, as regras do seguro ainda seguiam a legislação portuguesa, que era sujeita às normas comerciais da Europa. A legislação interna continuou precária até 1850.   
 
\ \ \ \ \ \ O Código Comercial Brasileiro<sup>7</sup>, Lei no 556/1850, promulgado em 25 de junho de 1850 estabelecia os direitos e deveres entre as partes contratantes. Portanto, o seguro marítimo foi pela primeira vez estudado e regulado em todos os seus aspectos. Com esta regulação, foi incentivada a criação de novas seguradoras no Brasil. Até então as seguradoras se voltavam para o comércio marítimo, apenas uma seguradora, a Argos Fluminense<sup>8</sup> , fundada em 1945, realizava seguros terrestres, e o seguro, antes do Código Comercial, era legítimo somente com a finalidade econômica de resguardar o patrimônio vivo dos senhores de escravos.   

\ \ \ \ \ \ Após o Código Comercial, as seguradoras que foram surgindo passaram a se dedicar aos seguros terrestres. “Companhia Tranquilidade” foi a primeira companhia de Seguros de Vida autorizada a funcionar no Brasil, em 1855, com sede no Rio de Janeiro, e a primeira a comercializar o Seguro de Vida. O ramo vida era até então proibido. Por volta de 1862, companhias de seguro estrangeiras, como a Companhia Garantia do Porto, Royal Insurance e Liverpool & London & Globo, instalaram filiais no país. Para isso, o governo criou em 1895 o Decreto no 234 que obrigada as seguradoras estrangeiras aqui instaladas a empregarem valores nacionais nas reservas de todas as apólices vigentes.   

\ \ \ \ \ \ Em 1901, as operações de seguro foram reguladas pelo Decreto no 4.270. Foram criadas as Inspetoria de Seguros (Superintendência Geral de Seguros), subordinadas ao Ministério da Fazenda. Mais tarde, em 1902, a Lei 953 modificou alguns aspectos do Decreto 4.270 para em 1903 promulgar o Decreto 5.072, o qual criou privilégios que não foram aceitas pela população, pois exploravam a boa fé do povo.   

\ \ \ \ \ \ Os seguros terrestres ganharam sua regulamentação específica em janeiro de 1917 com a entrada em vigor do Código Civil Brasileiro, que estabelecia regras gerais do contrato e definia as obrigações dos seguradores e dos segurados. Segundo Mendonça, “em 1930, o seguro de vida era o mais importante no ranking nacional, faturando 43% do total de prêmios do mercado.” Já em 1945, esse percentual caiu para 27,5% e, no final de 1984, era de 13,7%.   

\ \ \ \ \ \ Em 1916, ocorreu o maior avanço de ordem jurídica no campo do contrato de seguro: a promulgação do Código Civil Brasileiro (substituído pelo atual Código Civil Brasileiro de 2002). Nele, foram fixados os princípios essenciais do contrato de seguros e disciplinados os direitos e obrigações das partes, de modo a evitar conflitos entre os interessados. Foram esses princípios fundamentais que garantiram o desenvolvimento da instituição do seguro. Em 1929, surgiu a capitalização, com a criação da Sul América Capitalização S.A.   

\ \ \ \ \ \ Em 5 de dezembro de 1932, foi fundado o Sindicato de Corretores de Seguros, na cidade do Rio de Janeiro. Porém, a regulamentação dessa profissão só viria acontecer após 32 da criação do sindicato pela Lei 4.594 de 1964. E em 16 de maio de 1933 criaram o Sindicato dos Seguradores do Rio de Janeiro.    

\ \ \ \ \ \ Na década de 1930, o Governo de Vargas restringiu o fluxo de caixa para o exterior, que gerou uma debandada de várias seguradoras do país. Após, em 1937, foi criada uma tarifa mínima oficial para os seguros terrestres e marítimos, o que obrigava as companhias seguradoras a submeter suas tarifas para aprovação estatal.   

\ \ \ \ \ \ O Departamento Nacional de Seguros Privados (DNSPC) teve seu regulamento aprovado em 1934, que posteriormente foi substituído pela SUSEP – Superintendência de Seguros Privados.   

\ \ \ \ \ \ O governo criou, em 3 de abril de 1939, pelo Decreto-Lei no 1.186, o IRB- Instituto de Resseguros do Brasil, hoje IRB-Brasil Resseguros S/A. Desde então, as entidades seguradoras passaram a ressegurar<sup>9</sup> no IRB as responsabilidades que excedessem sua capacidade de retenção própria, que, através da retrocessão<sup>10</sup> , passou a compartilhar o risco com as sociedades seguradoras em operação no Brasil.   

\ \ \ \ \ \ A função inicial do IRB, que detinha o monopólio do resseguro no Brasil até 2007, era proteger as seguradoras nacionais por meio de pulverização de risco por resseguro automático e reter o valor dos prêmios<sup>11</sup> no Brasil. No seu primeiro ano de atividade, o IRB reteve aproximadamente 90% dos prêmios de resseguros-incêndio, setor que representava 75% do total de seguros à época, no Brasil. Novos produtos foram incluídos no rol do IRB com o tempo, por exemplo o resseguro-aeronáutico, em 1944, pioneiro no mundo.   

\ \ \ \ \ \ Um decreto de março de 1940 regulamentou as atividades de seguros privados, tornando obrigatórios os seguros contra risco de incêndio e transportes para comerciantes, indústrias e concessionárias de serviços públicos. Além disso, obrigou que companhias estrangeiras se organizassem como empresas brasileiras e constituíssem reservas no Brasil.   

\ \ \ \ \ \ A FENASEG – Federação Nacional das Empresas de Seguros Privados e de Capitalização foi fundada em 25 de junho de 1951, no Rio de Janeiro, entidade de representação sindical do mercado segurador.   

\ \ \ \ \ \ Em 1966, foi publicado o Decreto-Lei 73, que reformulou a política de seguros no Brasil e criou o SNSP – Sistema Nacional de Seguros Privados –, constituído pelo Conselho Nacional de Seguros Privados (CNSP); Superintendência de Seguros Privados (SUSEP); Instituto de Resseguros do Brasil (IRB); sociedades autorizadas a operar em seguros privados; e corretores habilitados. Esse decreto-lei foi considerado uma referência em termos de legislação, devido ao seu alcance e abrangência. As Companhias de Seguros devem obrigatoriamente possuir a forma de sociedades anônimas, sendo estas obrigadas a constituir e manter um capital social mínimo representado por ações nominativas.  

\ \ \ \ \ \ Em 1968, foi fundada a FENACOR – Federação Nacional dos Corretores de Seguros Privados, de Capitalização, de Previdência Privada e das Empresas Corretoras de Seguros. A federação tem por finalidade básica defender e proteger os interesses da categoria econômica que dela fazem parte, perante as entidades privadas e as autoridades públicas, além de colaborar com os poderes públicos no estudo e na solução de problemas relacionas à categoria e prestar assistência técnica e jurídica aos seus Sindicatos Filiados.   

\ \ \ \ \ \ O mercado de seguros, ciente das necessidades de formação técnica e aprimoramento das ciências do seguro, criou em 30 de junho de 1971 a FUNENSEG – Fundação Escola Nacional de Seguros –, responsável pelo ensino e divulgação do seguro no Brasil. Atualmente, a FUNENSEG chama-se Escola Nacional de Seguros e é mantenedora da ESNS – Escola Superior Nacional de Seguros –, única instituição de ensino superior a oferecer curso de graduação em Administração com Ênfase em Seguros e Previdência.   

\ \ \ \ \ \ Até 1977, os montepios<sup>12</sup>, operando sem a disciplina de regime legal próprio e sem o controle de um órgão fiscalizador, desfrutavam de vantajosa liberdade na concorrência com as seguradoras, estas tinham detalhadas regras legais. Em 1977 este quadro se alterou devido a promulgação da lei da previdência privada, que regulou os montepios e os fundos de pensão.   

\ \ \ \ \ \ Uma resolução de 1986 do CNSP fixou a participação de capital estrangeiro em empresas nacionais com o teto de 50% das ações, limitando em um terço do capital votante, exceto para os casos em que existisse interesse do governo brasileiro ou em casos de reciprocidade ou de acordos internacionais sancionados pelo presidente da República. Essa resolução foi revogada em 1998 pelo próprio CNSP, o que, com a estabilização da economia e a grande margem para exploração do mercado brasileiro, permitiu que companhias seguradoras estrangeiras aportassem em massa no país.   

\ \ \ \ \ \ No ano de 1998, foi criado o Conselho de Recursos do Sistema Nacional de Seguros Privados, de Previdência Complementar Aberta e de Capitalização – CRSNSP – como um órgão colegiado, integrante da estrutura básica do Ministério da Fazenda e que tem por finalidade o julgamento, em última instância administrativa, dos recursos de decisões dos órgãos fiscalizados do SNSP.   

\ \ \ \ \ \ O campo de abrangência do seguro é amplo. Porém, somente no século XX ocorreu a separação estatística entre as atividades de seguro em dois segmentos: o segmento de seguros de vida (life) e o segmento de seguros de não vida (non life).  

\ \ \ \ \ \ Em agosto de 2008, foi criada a Confederação Nacional das Empresas de Seguros Gerais, Previdência Privada e Vida, Saúde Suplementar e Capitalização – CNseg –, em assembleia, pelas federações associativas. A CNseg é a entidade máxima de representação institucional do mercado segurador, entendido como o conjunto dos setores de seguros, Previdência Complementar Aberta, Saúde Suplementar e Capitalização, tendo como missão congregar as principais lideranças, coordenar as ações políticas, representar o mercado junto às instituições nacionais e internacionais, elaborar o planejamento estratégico do segmento e desenvolver atividades comuns aos  interesses das federações.    

\ \ \ \ \ \ Cabem às federações a execução das funções e o desenvolvimento de ações no interesse específico das áreas representadas, ou seja:   

- A FenSeg (Federação Nacional de Seguros Gerais) atua na área de Seguros Gerais;<br/>
- A FenaPrevi (Federação Nacional de Previdência Privada e Vida) atua na área de Previdência Complementar Aberta; <br/>
- A FenaSaúde (Federação Nacional de Saúde Suplementar) atua na área de Saúde Complementar privada; e <br/>
- A FENACAP (Federação Nacional de Capitalização) atua na área de capitalização. 

\ \ \ \ \ \ A FENASEG continua sendo a entidade de representação sindical do mercado segurador. A ela estão filiados os oito Sindicatos Regionais: Bahia (Sergipe/Tocantins), Minas Gerais, Pernambuco (Norte/Nordeste), Paraná, Rio de Janeiro/Espírito Santo, Rio Grande do Sul, Santa Catarina e São Paulo.   

\ \ \ \ \ \ Em junho de 2012, a SUSEP iniciou a normatização e a regulamentação do Microsseguro, cuja operação tem um mercado principal estimado para atingir 128 milhões de brasileiros.   

\ \ \ \ \ \ No Brasil, a intermediação entre seguradora e segurado é feita, obrigatoriamente, por corretores de seguros certificados pela FUNENSEG, relação que tem mudado rapidamente com o advento da internet, proporcionando maior acesso a informações pelos clientes, além de cotações e comparações mais rápidas entre diversas entidades seguradoras.  

_________________
  <sup>1</sup>Mutualística: Relativo a mutualismo (Michaellis,2017); Mutualismo: Sistema de associação assente nos princípios de ajuda recíproca entre os seus membros e de contribuiçãocoletiva para benefício de cada um dos membros (Aurélio, 2017).
  
  <sup>2</sup>Hamurábi: Imperador da Babilônia entre 2067 a 2025 A.C..
  
  <sup>3</sup>*Lex Rhodia*: Compilação romana de leis marítimas. A Ilha de Rodes, Grécia, famosa pelo Colosso de Rodes, uma das sete maravilhas do mundo antigo, dá nome ao conjunto de leis devido a sua importância nas rotas marítimas transnacionais já desde o século IX A.C. (RIBEIRO, P. G., 1994)
  
  <sup>4</sup>Avaria Grossa: “avaria grossa é toda despesa extraordinária ou dano causado ao navio ou à carga, voluntariamente, em benefício comum de ambos. (Glossário de Terminologia Técnica Comercial Marítima, FUNENSEG, 2002, p. 7)
  
  <sup>5</sup>Sinistro: Ocorrência de acidente ou perda preestabelecida em contrato durante a vigência do contrato.
  
  <sup>6</sup>Visconde de Cairu: José da Silva Lisboa (1756-1835), foi um político brasileiro da época do Brasil Império. Foi assessor direto do Príncipe Regente D. João VI para assuntos econômicos, mais tarde se tornou Senador do Império.
  
  <sup>7</sup>Código Comercial Brasileiro de 1850, disponível em: http://bit.ly/2j8DJjq <acesso em 17/12/2017>
  
  <sup>8</sup>Hoje Chubb do Brasil Cia. De Seguros.
  
  <sup>9</sup>Resseguro: seguro realizado por empresa seguradora, no qual  segurador se responsabiliza, total ou parcialmente, pelo risco de uma operação já coberta por outro segurador.
  
  <sup>10</sup>Retrocessão: “Resseguro do Resseguro”. A companhia resseguradora devolve às seguradoras parte do risco assumido.
  
  <sup>11</sup>Prêmio: valor pago pelo segurado a seguradora. É o preço do seguro.
  
  <sup>12</sup>Montepios: Instituições em que, mediante o pagamento de cotas, cada membro adquire o direito de, por morte, deixar pensão pagável a alguém de sua escolha. São essas as manifestações mais antigas de previdência social.

<br>


# Referências

- AZEVEDO, G. H. W., **Seguros, Matemática Atuarial e Financeira: uma abordagem introdutória.** Editora Saraiva. São Paulo, 2008.
  
- CONTADOR, C. R., FERRAZ, C. B. **Uma contribuição à história do seguro no Brasil.** Instituto CO PPEAD de Administração da Universidade Federal do Rio de Janeiro – Rio de Janeiro, 2000.
  
- ESCOLA NACIONAL DE SEGUROS. **Conceitos básicos de seguros.** Supervisão e Coordenação  metodológica   da Diretoria de Ensino Técnica de Alessandra Teixeira – 12. Ed. – Rio de Janeiros; Funenseg, 2015.
  
- ESCOLA NACIONAL DE SEGUROS. **Seguro DPVAT.** Supervisão e Coordenação metodológica da Diretoria de Ensino Técnica de Alessandra Teixeira – 2. Ed. – Rio de Janeiros; Funenseg, 2015.
  
- GUIMARÃES, S. R. Fundamentação Atuarial dos seguros de vida: um estudo comparativo entre os seguros   de vida individual e em grupo. **Série de Cadernos de Seguro: teses,** v. 9, no 20. FUNENSEG, Rio    de Janeiro, 2004.
  
- MENDONÇA, L. A trajetória de seguros de vida, em alguns flashes. **Cadernos de Seguro** – Coletânea   1981 – 2001.
  
- RIBEIRO, P. G. **História do seguro: um resumo.** Fundação Escola Nacional de Seguros. Rio de janeiro: FUNENSEG, ago. 1994.
