---
title: "Tábua de mortalidade IBGE"
---

### Tábua de mortalidade IBGE  

\ \ \ \ \ \ Em cumprimento ao disposto no Art. 2o do Decreto no 3.266, de 29 de novembro de 1999, o IBGE divulga, anualmente, até o dia primeiro de dezembro de cada ano, a Tábua Completa de Mortalidade para o total da população brasileira com data de referência em 1° de julho do ano anterior.   

<div class="panel panel-primary">
  <div class="panel-body">
  “Art. 2°. Compete ao IBGE publicar, anualmente, até o dia primeiro de dezembro, no Diário Oficial da União, a tábua completa de mortalidade para o total da população brasileira referente ao ano anterior. ”
</div>
</div>

\ \ \ \ \ \ A tábua de mortalidade anualmente divulgada tem sido utilizada pelo Ministério da Previdência Social (MPS) como um dos parâmetros necessários na determinação do chamado fator previdenciário para o cálculo dos valores relativos às aposentadorias dos trabalhadores que estão sob o Regime Geral de Previdência Social.  

\ \ \ \ \ \ De acordo com Wilbert (2013), a tábua completa de mortalidade construída pelo IBGE e adotada pelo RGPS é pouco utilizada pelo mercado previdenciário e securitário por apresentarem taxas relativas ao conjunto da população, que são diferentes das observadas entre a massa de participantes desse mercado.  

\ \ \ \ \ \ A Tábua de Mortalidade de 2010 é uma projeção com base na mortalidade calculada para os anos de 1980, 1991 e 2000, as quais resultaram de uma ampla discussão durante uma oficina de trabalho entre Técnicos da Coordenação de População e Indicadores Sociais (COPIS/DPE/IBGE) e do Centro Latinoamericano y Caribeño de Demografía (CELADE/CEPAL/Nações Unidas). Sendo que, também em 2010, o IBGE divulgou a Tábua Abreviada de Mortalidade. A tábua abreviada de mortalidade é proveniente de uma projeção da mortalidade feita a partir da Tábua Completa de Mortalidade de 2010.  

\ \ \ \ \ \ Já as tábuas (completas) construídas a partir de 2011 são provenientes de uma projeção dos níveis de mortalidade a partir da Tábua de Mortalidade construída para o ano de 2010. Trata-se de um procedimento necessário de atualização, quando se trabalha com indicadores e/ou modelos demográficos prospectivos. Além disso, o desenvolvimento desta atividade cumpre, também, o propósito de gerar parâmetros atualizados da mortalidade do Brasil que foram incorporados à Projeção da População por Sexo e Idade para o Período 2000-2060.   

\ \ \ \ \ \ É necessário, porém, salientar que a tábua de mortalidade, ou tábua de vida elaborada pelo IBGE constitui um modelo demográfico que descreve a incidência da mortalidade ao longo do ciclo vital das pessoas. Como principais indicadores extraídos da tábua de mortalidade podem ser citados os seguintes: 

  1. As probabilidades de morte entre duas idades exatas, em particular, a   probabilidade de um recém-nascido falecer antes de completar o primeiro ano de vida, também conhecida como a taxa de mortalidade infantil;   
  2.  As expectativas de vida a cada idade, em especial, a expectativa de vida ao nascimento.   

\ \ \ \ \ \ Tais indicadores guardam associação direta com as condições sanitárias, de saúde e de segurança da população em estudo, constituindo um modelo de grande valor para avaliar e introduzir os ajustes necessários nas políticas sociais voltadas para a sociedade como um todo.  


### Referências
- WILBERT, M. D., DE LIMA, D. V., GOMES, M. M. F. O Impacto da Utilização de Diferentes Tábuas de Mortalidade nas Estimativas de Pagamento de Benefícios no RGPS. **Rev. Brasileira de Risco e Seguro**. Rio de Janeiro, v. 8, n. 16, p. 19-40, 2013.

- BRASIL. **IBGE**. Tábuas Completas de Mortalidade. Disponível em < https://www.ibge.gov.br/estatisticas-novoportal/sociais/populacao/9126-tabuas-completas-de-mortalidade.html?=&t=o-que-e>. Acesso em: 05 de julho de 2018.  

- BRASIL. **IBGE**. Tábuas Abreviadas de Mortalidade. Disponível em <https://www.ibge.gov.br/estatisticas-novoportal/sociais/populacao/9125-tabuas-abreviadas-de-mortalidade.html?=&t=o-que-e>. Acesso em: 05 de julho de 2018.

